name: Docker Build and Test

on:
  push:
    paths:
      - 'Dockerfile'
  pull_request:
    paths:
      - 'Dockerfile'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build . --file Dockerfile -t cuda-test-image

      - name: Test Docker image
        run: |
          docker run --rm cuda-test-image python -c "import torch; print(torch.__version__)"
          docker run --rm cuda-test-image zsh -c "echo 'ZSH is available'"
